/*
 * This source file was generated by the Gradle 'init' task
 */
package org.custour;

public class App {
	public String getGreeting() {
		return "Heeeee World!";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());
	}
}
